// resources/js/components/app-sidebar.tsx
import AppLogo from '@/components/app-logo';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { dashboard } from '@/routes';
import { type NavItem } from '@/types';
import { Link } from '@inertiajs/react';
import {
  ArrowFatLinesLeftIcon,
  ArrowFatLinesRightIcon,
} from '@phosphor-icons/react';
import { BookOpen, Folder, LayoutGrid } from 'lucide-react';
import { useState } from 'react';

const mainNavItems: NavItem[] = [
  {
    title: 'Dashboard',
    href: dashboard(),
    icon: LayoutGrid,
  },
];

const footerNavItems: NavItem[] = [
  {
    title: 'Repository',
    href: 'https://github.com/laravel/react-starter-kit',
    icon: Folder,
  },
  {
    title: 'Documentation',
    href: 'https://laravel.com/docs/starter-kits#react',
    icon: BookOpen,
  },
];

interface AppSidebarProps {
  className?: string;
}

export function AppSidebar({ className }: AppSidebarProps) {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  return (
    <aside
      className={cn(
        `row-span-full overflow-y-auto rounded-r-2xl bg-grey-900 p-4 text-white transition-all duration-300 ${
          sidebarOpen ? 'w-[300px]' : 'w-[88px]'
        }`,
        className,
      )}
    >
      <header className="flex items-center justify-center text-2xl font-bold text-white">
        <Button variant="ghost" className="w-full hover:bg-grey-100" asChild>
          <Link href={dashboard()} prefetch>
            <AppLogo />
          </Link>
        </Button>
      </header>
      <div onClick={() => setSidebarOpen(!sidebarOpen)}>
        {sidebarOpen ? (
          <span className="flex items-center justify-start gap-4 text-grey-300">
            <ArrowFatLinesLeftIcon weight="fill" size={24} color={'#b3b3b3'} />
            Minimize Menu
          </span>
        ) : (
          <ArrowFatLinesRightIcon weight="fill" size={24} color={'#b3b3b3'} />
        )}
      </div>
    </aside>
    // <Sidebar collapsible="icon" variant="floating" className="">
    //   <SidebarHeader>
    //     <SidebarMenu>
    //       <SidebarMenuItem>
    //         <SidebarMenuButton size="lg" asChild>
    //           <Link href={dashboard()} prefetch>
    //             <AppLogo />
    //           </Link>
    //         </SidebarMenuButton>
    //       </SidebarMenuItem>
    //     </SidebarMenu>
    //   </SidebarHeader>
    //
    //   <SidebarContent>
    //     <NavMain items={mainNavItems} />
    //   </SidebarContent>
    //
    //   <SidebarFooter>
    //     <NavFooter items={footerNavItems} className="mt-auto" />
    //     <NavUser />
    //   </SidebarFooter>
    // </Sidebar>
  );
}

// resources/js/components/AppSidebar.vue
<script setup lang="ts">
import NavMain from '@/components/NavMain.vue';
import NavUser from '@/components/NavUser.vue';
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from '@/components/ui/sidebar';
import { dashboard } from '@/routes';
import { type NavItem } from '@/types';
import { Link } from '@inertiajs/vue3';
import {
    ArrowUpDown,
    ChartPie,
    LayoutGrid,
    Receipt,
    Settings,
    Vault,
} from 'lucide-vue-next';
import AppLogo from './AppLogo.vue';

const mainNavItems: NavItem[] = [
    {
        title: 'Dashboard',
        href: dashboard(),
        icon: LayoutGrid,
    },
    {
        title: 'Transactions',
        href: '/transactions',
        icon: ArrowUpDown,
    },
    {
        title: 'budgets',
        href: '/budgets',
        icon: ChartPie,
    },
    {
        title: 'Pots',
        href: '/pots',
        icon: Vault,
    },
    {
        title: 'Recurring Bills',
        href: '/recurring-bills',
        icon: Receipt,
    },
    {
        title: 'App Settings',
        href: '/app-settings',
        icon: Settings,
    },
];

// const footerNavItems: NavItem[] = [
//     {
//         title: 'Github Repo',
//         href: 'https://github.com/laravel/vue-starter-kit',
//         icon: Folder,
//     },
//     {
//         title: 'Documentation',
//         href: 'https://laravel.com/docs/starter-kits#vue',
//         icon: BookOpen,
//     },
// ];
</script>

<template>
    <Sidebar collapsible="icon" variant="inset">
        <SidebarHeader>
            <SidebarMenu>
                <SidebarMenuItem>
                    <SidebarMenuButton size="lg" as-child>
                        <Link :href="dashboard()">
                            <AppLogo />
                        </Link>
                    </SidebarMenuButton>
                </SidebarMenuItem>
            </SidebarMenu>
        </SidebarHeader>

        <SidebarContent>
            <NavMain :items="mainNavItems" />
        </SidebarContent>

        <SidebarFooter>
            <!--            <NavFooter :items="footerNavItems" />-->
            <NavUser />
        </SidebarFooter>
    </Sidebar>
    <slot />
</template>
